---
title: "CDS101 Final Project"
author: "Tyson Johnson"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(infer))
# Load data
wages_by_education <- read.csv("wages_by_education.csv")
wages_tidy <- read.csv("wages_tidy.csv")
wages_sep <- read.csv("wages_sep.csv")
```

<!-- This chunk creates wages_tidy -->
<!-- ```{r} -->
<!-- wages_tidy <- wages_by_education %>%  -->
<!--   pivot_longer( -->
<!--     !year, -->
<!--     names_to = "demographic", -->
<!--     values_to = "wages" -->
<!--   ) -->
<!-- ``` -->


<!-- This chunk writes wages_tidy.csv -->
<!-- ```{r} -->
<!-- wages_tidy %>%  -->
<!--   write.csv("wages_tidy.csv", row.names = FALSE) -->
<!-- ``` -->

## Summary Table

```{r}
wages_tidy %>% 
  group_by(demographic) %>% 
  summarize(
    mean = mean(wages, na.rm=TRUE), 
    median = median(wages, na.rm=TRUE),
    min = min(wages, na.rm=TRUE), 
    max = max(wages, na.rm=TRUE), 
    sd = sd(wages, na.rm=TRUE), 
    iqr = IQR(wages, na.rm=TRUE)
  )
```

\pagebreak

```{r}
wages_tidy %>%
 filter(grepl("black", demographic)) %>%
 filter(!grepl("men", demographic)) %>%
 ggplot() +
 geom_line(
   mapping = aes(
     x = year,
     y = wages,
     color = demographic
   )
 )
```

```{r}
wages_ethnicity <- wages_tidy %>%
 filter(grepl(c("black|hispanic|white"), demographic)) %>%
 separate(demographic, into = c("ethnicity", "demographic"),
          sep = "_", extra = "merge") %>%
 arrange(ethnicity, demographic, year)

wages_ethnicity_inverse <- wages_tidy %>%
 filter(!grepl(c("black|hispanic|white"), demographic)) %>%
 mutate(ethnicity = NA) %>%
 relocate(ethnicity, .after = year)
wages_ethnicity_combined <- wages_ethnicity %>%
 bind_rows(wages_ethnicity_inverse) %>%
 arrange(ethnicity, demographic, year)
```

```{r}
wages_gender <- wages_ethnicity_combined %>%
 filter(grepl(c("men|women"), demographic)) %>%
 separate(demographic, into = c("gender", "demographic"),
          sep = "_", extra = "merge") %>%
 arrange(ethnicity, gender, demographic, year)
wages_gender_inverse <- wages_ethnicity_combined %>%
 filter(!grepl(c("men|women"), demographic)) %>%
 mutate(gender = NA) %>%
 relocate(gender, .after = ethnicity)
wages_gender_combined <- wages_gender %>%
 bind_rows(wages_gender_inverse) %>%
 arrange(ethnicity, gender, demographic, year)
```

```{r}
wages_sep <- wages_gender_combined
wages_sep %>%
 write.csv("wages_sep.csv", row.names=FALSE)
```

```{r}
wages_final <- wages_sep

wages_final$demographic <- factor(wages_final$demographic, 
                                levels = c("advanced_degree", 
                                           "bachelors_degree", 
                                           "some_college", 
                                           "high_school", 
                                           "less_than_hs"), 
                                labels = c("Advanced Degree", 
                                           "Bachelors Degree", 
                                           "Some College", 
                                           "High School", 
                                           "Less than High School"), 
                                ordered = TRUE)
```

```{r}
na.exclude(wages_final) %>% 
  ggplot() + 
  geom_line(
    mapping = aes(
      x = year,
      y = wages, 
      color = demographic
    )
  ) + 
  facet_wrap(
    gender ~ ethnicity,
    ncol = 3
  ) + 
  theme(
    axis.text.x = element_text(angle = 30)
  ) +
  labs(
    color = "Demographic"
  ) + 
  scale_color_manual(
    values = c("red", "orange", "blue", "green", "purple")
  )
```

